name: 'S3 Deploy'
description: 'Deploy an SPA to S3 using branch and version sub directories'
author: 'The Concord Consortium'
outputs:
  deployPath:
    description: 'The location where the files will be stored'
runs:
  using: 'node12'
  main: 'dist/index.js'
