name: 'S3 Deploy'
description: 'Deploy an SPA to S3 using branch and version sub directories'
author: 'The Concord Consortium'
inputs:
  awsAccessKeyId:
    description: AWS access key id
    required: true
  awsSecretAccessKey:
    description: AWS secret access key
    required: true
  bucket:
    description: S3 Bucket to deploy files to
    required: true
  prefix:
    description: S3 prefix to prepend to files uploaded to S3
    required: true
  noPrefix:
    description: If "true" the prefix is not used for the top level bucket
    required: false
  topBranches:
    description: A JSON array of branch names (without PT number) for which the
      index-top.html file will be copied to the top. The file name will be
      [prefix]/index-[branchName].html
    required: false
  workingDirectory:
    description: Directory where the build command will be run.
      Default is the top level.
    required: false
  build:
    description: build command to run.
      Default is 'npm run build'
    required: false
  folderToDeploy:
    description: the folder created by the build command that should be deployed.
      It is relative to the workingDirectory if that is set.
      Default is 'dist'
    required: false
  maxBranchAge:
    description: If present (and it is a valid decimal value) it will be used as the
      max-age parameter for the aws sync command when copying files for branch deploys.
      This overrides the built-in value for branch deploys.
    required: false
  maxVersionAge:
    description: If present (and it is a valid decimal value) it will be used as the
      max-age parameter for the aws sync command when copying files for version deploys.
      This overrides the built-in value for version deploys.
    required: false
  deployRunUrl:
    description: "Templated string for the URL to run the deployed files. The string can
      contain the following placeholder: __deployPath__"
    required: true
outputs:
  deployPath:
    description: An additional path added to the prefix.
      If it is a tag build it will be '/version/{tag-name}'.
      If it is a branch build it will be '/branch/{branch-name}'.
  logUrl:
    description: Full URL for the deployment.
runs:
  using: 'node20'
  main: 'dist/index.js'
