name: 'S3 Deploy'
description: 'Deploy an SPA to S3 using branch and version sub directories'
author: 'The Concord Consortium'
inputs:
  awsAccessKeyId:
    description: AWS access key id
    required: true
  awsSecretAccessKey:
    description: AWS secret access key
    required: true
  bucket:
    description: S3 Bucket to deploy files to
    required: true
  prefix:
    description: S3 prefix to prepend to files uploaded to S3
    required: true
  topBranches:
    description: A JSON array of branch names (without PT number) for which the
      index-top.html file will be copied to the top. The file name will be
      [prefix]/index-[branchName].html
    required: false
  workingDirectory:
    description: Directory where the build command will be run.
      Default is the top level.
    required: false
  build:
    description: build command to run.
      Default is 'npm run build'
    required: false
  folderToDeploy:
    description: the folder created by the build command that should be deployed.
      It is relative to the workdingDirectory if that is set.
      Default is 'dist'
    required: false
outputs:
  deployPath:
    description: 'The location where the files will be stored'
runs:
  using: 'node12'
  main: 'dist/index.js'
